### ISSUE TITLE
Placeholder for peer review

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/recipe-plugin#1]
Please leave peer review comments on the module here.

Link back to main issue: https://github.com/silverstripe/silverstripe-framework/issues/6860

You can test using the following recipes:

- `tractorcow/recipe-core`
- `tractorcow/recipe-cms`

Note that until we move this to silverstripe org, the plugin is `tractorcow/recipe-plugin`, although the docs are written with the final name in mind. :)

**Comment by flamerohr** [comment]
The readme seems incorrect, as this is tagged in the `1` branch, you'd expect the command to create a project to be:
`$ composer create-project silverstripe/recipe-cms ./myssproject ^1.0@dev`
but it is documented to be
`$ composer create-project silverstripe/recipe-cms ./myssproject ^4.0@dev`
So there is a bit of inconsistency with the expected version number for recipe to the version number of the `cms`

having said that, once the project is installed, works as expected with the `recipe-cms` modules inlined, then if you wanted to inline `recipe-core` you'd need to `composer require-recipe silverstripe/recipe-core ^1.0@dev` afterwards.

I would like to request that the documentation clearly describes the inlining process (e.g. with its own title) rather than how it is currently stated as a passing note in the create project title.

when I run `$ composer require-recipe silverstripe/recipe-cms ^1.0@dev` after the `create-project` above, I get the following error:
```
  [ErrorException]                          
  Undefined index: silverstripe/recipe-cms 
```

<details>
<summary>Error details can be found here</summary>
Reading ./composer.json
Loading config file /Users/cjoe/.composer/config.json
Loading config file /Users/cjoe/.composer/auth.json
Loading config file ./composer.json
Checked CA file /usr/local/etc/openssl/cert.pem: valid
Executing command (/Users/cjoe/Sites/silverstripe/ss4-test): git branch --no-color --no-abbrev -v
Reading /Users/cjoe/.composer/composer.json
Loading config file /Users/cjoe/.composer/config.json
Loading config file /Users/cjoe/.composer/auth.json
Loading config file /Users/cjoe/.composer/composer.json
Loading config file /Users/cjoe/.composer/auth.json
Reading /Users/cjoe/.composer/auth.json
Reading /Users/cjoe/Sites/silverstripe/ss4-test/vendor/composer/installed.json
Reading /Users/cjoe/.composer/vendor/composer/installed.json
Loading plugin Composer\Installers\Plugin
Loading plugin SilverStripe\RecipePlugin\RecipePlugin
Running 1.2.0 (2016-07-19 01:28:52) with PHP 7.1.5 on Darwin / 15.6.0
Reading ./composer.lock

                                            
  [ErrorException]                          
  Undefined index: silverstripe/recipe-cms  
                                            

Exception trace:
 () at /Users/cjoe/Sites/silverstripe/ss4-test/vendor/silverstripe/recipe-plugin/src/RecipeCommandBehaviour.php:150
 Composer\Util\ErrorHandler::handle() at /Users/cjoe/Sites/silverstripe/ss4-test/vendor/silverstripe/recipe-plugin/src/RecipeCommandBehaviour.php:150
 SilverStripe\RecipePlugin\RequireRecipeCommand->findInstalledVersion() at /Users/cjoe/Sites/silverstripe/ss4-test/vendor/silverstripe/recipe-plugin/src/RequireRecipeCommand.php:60
 SilverStripe\RecipePlugin\RequireRecipeCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:844
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:231
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:104
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:24

require-recipe <recipe> [<version>]
</details>

**Comment by tractorcow** [comment]
@flamerohr I've fixed that crash in a commit in https://github.com/silverstripe/recipe-plugin/pull/3

I've also pushed up a documentation update which should cover your issues raised.

**Comment by flamerohr** [comment]
Cheers, happy with the first half of that pull request, I'll review the second half later today :)
